services:
  mysql:
    image: mysql:8.0
    container_name: decoy_EM_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: decoy_event_management
    ports:
      - "3162:3306"
    volumes:
      - decoy_EM_db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5

volumes:
  decoy_EM_db_data: