spring.application.name=event-managment

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:9090/decoy_event_management}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:root}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

management.endpoints.web.base-path=/
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always